version: "3.8"

services:
  patient-service:
    build: .
    ports:
      - 8002:8002
    depends_on:
      - my-mongodb
    networks:
      - mynetwork

  my-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
  
