apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient-app
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8002
      targetPort: 8002
    - name: grpc
      protocol: TCP
      port: 5002
      targetPort: 5002